name: Release APK on GitHub

on:
  push:
    tags:
      - '*'

jobs:

  release:

    name: Release APK on GitHub
    runs-on: macos-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Create local.properties file
        env:
          accessToken: ${{ secrets.ACCESS_TOKEN }}
          storePassword: ${{ secrets.STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        run: |
          echo accessToken=$accessToken > ./local.properties
          echo storePassword=$storePassword >> ./local.properties
          echo keyPassword=$keyPassword >> ./local.properties

      - name: Run unit tests
        run: ./gradlew test

      - name: Run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          profile: Nexus 6
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck

      - name: Generate APK
        run: ./gradlew assembleRelease

      - name: Create GitHub release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact: "app/build/outputs/apk/release/ReleaseTracker-release.apk"
          artifactContentType: "application/vnd.android.package-archive"
          bodyFile: "CHANGELOG.md"
          artifactErrorsFailBuild: true